name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool

    - name: Run configure script
      run: |
        chmod +x configure
        ./configure

    - name: Build
      run: make

    - name: Run tests
      run: make check

    - name: Run distcheck
      run: make distcheck
